In [ ]:
# this notebooks demostrates deep learning applied to linear regression

# notably, the difference between L2 loss and L1 loss should be considered

In [1]:
import torch
import torch.nn.functional as F



In [124]:
X = torch.tensor([1,1], dtype=torch.float)
W = torch.tensor([[3,2], [2,2]], dtype=torch.float, requires_grad=True)
Y = torch.tensor([3,3], dtype=torch.float)

a = X @ W 

# l = torch.pow(torch.pow((X - Y), 2).sum(-1), .5)
# l = torch.abs(a - Y).sum(-1)
l = F.mse_loss(a, Y)


In [125]:
a

tensor([5., 4.], grad_fn=<SqueezeBackward4>)

In [126]:
l.backward()

In [127]:
l

tensor(2.5000, grad_fn=<MseLossBackward0>)

In [128]:
print(W)
print('\n')
print(W.grad)


tensor([[3., 2.],
        [2., 2.]], requires_grad=True)


tensor([[2., 1.],
        [2., 1.]])
